### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by shrx** [choonkeat/branchesapp#2]
```
$ ruby g2h.rb https://github.com/popcorn-time/popcorn-app
#<URI::HTTPS:0x007ffa8c26c170 URL:https://api.github.com/repos/popcorn-time/popcorn-app/forks>
/Users/shrx/Downloads/branchesapp-master/lib/github.rb:26:in `forks': #<Net::HTTPForbidden 403 Forbidden readbody=true>{"message":"API rate limit exceeded for IP_ADDRESS. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"} (RuntimeError)
	from /Users/shrx/Downloads/branchesapp-master/lib/github.rb:58:in `fetch_all'
	from g2h.rb:99:in `<main>'
```
Is it possible to add authentication to raise the request limit?

**Comment by choonkeat** [comment]
thanks for reporting @shrx! please update your code and set the `HTTP_USER` and `HTTP_PASSWORD` environment variables. See https://github.com/choonkeat/branchesapp#rate-limit

**Comment by shrx** [comment]
Thanks for the quick fix.
